services:
  - type: web
    name: gym-app
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - fromGroup: gym-app-secrets
      - key: SERVER_PORT
        value: 8080

databases:
  - name: gym-db
    plan: free
